#include "qt_ui/MainWindow.h"
#include "ui_MainWindow.h"  // Generated by Qt MOC - should match the class name in the UI file
#include "qt_ui/QtUtils.h"
#include "menu_system/menu_system.h"
#include "image_processing/image_processing.h"
#include <QVBoxLayout>
#include <QFileDialog>
#include <QMessageBox>
#include <QFileInfo>
#include <QDir>
#include <opencv2/imgcodecs.hpp>

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
    , imageView(new ImageView(this))
{
    ui->setupUi(this);
    initializeUi();
    connectSignals();
}

MainWindow::~MainWindow()
{
    // The unique_ptr will automatically delete ui
    // imageView is deleted by Qt's parent-child relationship
}

void MainWindow::initializeUi()
{
    // Add ImageView to the image view container
    QVBoxLayout* layout = qobject_cast<QVBoxLayout*>(ui->imageViewContainer->layout());
    if (layout) {
        layout->addWidget(imageView);
    }
    
    // Set window title
    setWindowTitle("MIB Studio");
    
    // Set statusbar message
    statusBar()->showMessage("Ready");
}

void MainWindow::connectSignals()
{
    // Connect ImageView signals
    connect(imageView, &ImageView::zoomChanged, [this](double level) {
        statusBar()->showMessage(QString("Zoom: %1%").arg(level * 100.0, 0, 'f', 0));
    });
    
    connect(imageView, &ImageView::imageClicked, [this](QPoint point) {
        statusBar()->showMessage(QString("Position: (%1, %2)").arg(point.x()).arg(point.y()));
    });
}

void MainWindow::on_actionOpen_triggered()
{
    QString filePath = QFileDialog::getOpenFileName(
        this,
        "Open Image",
        QDir::homePath(),
        "Image Files (*.png *.jpg *.bmp *.tif);;All Files (*.*)"
    );
    
    if (!filePath.isEmpty()) {
        loadImageFile(filePath);
    }
}

void MainWindow::on_actionSave_triggered()
{
    // Placeholder for save functionality
    QMessageBox::information(this, "Save", "Save functionality will be implemented in future phases.");
}

void MainWindow::on_actionExit_triggered()
{
    close();
}

void MainWindow::on_actionRunMockSample_triggered()
{
    QString folderPath = QFileDialog::getExistingDirectory(
        this,
        "Select Sample Directory",
        QDir::homePath(),
        QFileDialog::ShowDirsOnly
    );
    
    if (!folderPath.isEmpty()) {
        runMockSample(folderPath);
    }
}

void MainWindow::on_actionRunLiveSample_triggered()
{
    runLiveSample();
}

void MainWindow::on_actionConvertSavedImages_triggered()
{
    QString filePath = QFileDialog::getOpenFileName(
        this,
        "Select Binary Image File",
        QDir::homePath(),
        "All Files (*.*)"
    );
    
    if (filePath.isEmpty()) {
        return;
    }
    
    QString outputDir = QFileDialog::getExistingDirectory(
        this,
        "Select Output Directory",
        QDir::homePath(),
        QFileDialog::ShowDirsOnly
    );
    
    if (!outputDir.isEmpty()) {
        convertSavedImages(filePath, outputDir);
    }
}

void MainWindow::on_openFileButton_clicked()
{
    on_actionOpen_triggered();
}

void MainWindow::on_openFolderButton_clicked()
{
    QString folderPath = QFileDialog::getExistingDirectory(
        this,
        "Open Image Folder",
        QDir::homePath(),
        QFileDialog::ShowDirsOnly
    );
    
    if (!folderPath.isEmpty()) {
        loadImageFolder(folderPath);
    }
}

void MainWindow::on_runMockSampleButton_clicked()
{
    on_actionRunMockSample_triggered();
}

void MainWindow::on_runLiveSampleButton_clicked()
{
    on_actionRunLiveSample_triggered();
}

void MainWindow::on_convertSavedImagesButton_clicked()
{
    on_actionConvertSavedImages_triggered();
}

void MainWindow::on_actionAbout_triggered()
{
    QMessageBox::about(this, "About MIB Studio",
        "MIB Studio\n"
        "Version 1.0\n\n"
        "A cell analysis application for microscopy images.\n");
}

void MainWindow::on_actionPreferences_triggered()
{
    // Placeholder for preferences dialog
    QMessageBox::information(this, "Preferences", "Preferences dialog will be implemented in future phases.");
}

void MainWindow::loadImageFile(const QString& filePath)
{
    // Load image using OpenCV
    cv::Mat image = cv::imread(filePath.toStdString());
    
    if (image.empty()) {
        QMessageBox::warning(this, "Error", "Failed to load image: " + filePath);
        return;
    }
    
    // Set image in the image view
    imageView->setImage(image);
    
    // Update status bar
    QFileInfo fileInfo(filePath);
    statusBar()->showMessage("Loaded: " + fileInfo.fileName() + 
                           " | Size: " + QString::number(image.cols) + "x" + 
                           QString::number(image.rows));
    
    // Switch to image tab
    ui->contentTabWidget->setCurrentIndex(0);
}

void MainWindow::loadImageFolder(const QString& folderPath)
{
    // Placeholder for loading a folder of images
    QMessageBox::information(this, "Load Folder", 
        "Folder loading functionality will be implemented in future phases.\n"
        "Selected folder: " + folderPath);
}

void MainWindow::runMockSample(const QString& folderPath)
{
    // Placeholder for running mock sample
    // In future phases, this will interface with the existing mock sample code
    QMessageBox::information(this, "Run Mock Sample", 
        "Mock sample functionality will be implemented in future phases.\n"
        "Selected folder: " + folderPath);
    
    // For demonstration purposes only - will be replaced with actual implementation
    QDir dir(folderPath);
    QStringList filters;
    filters << "*.png" << "*.jpg" << "*.bmp" << "*.tif";
    QStringList imageFiles = dir.entryList(filters, QDir::Files);
    
    if (!imageFiles.isEmpty()) {
        // Just load the first image for now
        QString imagePath = folderPath + QDir::separator() + imageFiles.first();
        loadImageFile(imagePath);
    }
}

void MainWindow::runLiveSample()
{
    // Placeholder for running live sample
    QMessageBox::information(this, "Run Live Sample", 
        "Live sample functionality will be implemented in future phases.");
}

void MainWindow::convertSavedImages(const QString& filePath, const QString& outputDir)
{
    // Placeholder for converting saved images
    QMessageBox::information(this, "Convert Saved Images", 
        "Image conversion functionality will be implemented in future phases.\n"
        "Selected file: " + filePath + "\n"
        "Output directory: " + outputDir);
} 